### ISSUE TITLE
Sane default settings for DNS

### ISSUE THREAD

**Issue by whiskeysierra** [zalando-incubator/put-it-to-rest#2]
> What happened:
* after the traffic of the broken DOP service was switched, our cart service did not issue requests to the new stack but rather to the old broken stack, only a respawn of the instances solved this issue
* we could reproduce it on release staging with the help of Rodrigo
* we could reproduce it on a local machine switching services via /etc/hosts
* -> key was to have constant traffic on the cart service to reproduce the behaviour

> *The connection pool for the apache HTTP Client keeps the connection for too long, so it cannot be closed and renewed*
> * HttpClient knows about a ConnectionManager
> * org.apache.http.impl.conn.PoolingHttpClientConnectionManager has a default constructor that does not specify an end of life for connection before the year ~30000000
> * setting this ttl to some value > 0 instantly allowed for the correct behaviour

**Comment by lukasniemeier-zalando** [comment]
See [here](https://github.com/zalando-incubator/put-it-to-rest/blob/master/src/main/java/org/zalando/putittorest/HttpClientFactoryBean.java#L30), solved?

**Comment by lukasniemeier-zalando** [comment]
Maybe increase to 60 seconds...

**Comment by whiskeysierra** [comment]
> Maybe increase to 60 seconds...

Or make it configurable :stuck_out_tongue_winking_eye:

**Comment by whiskeysierra** [comment]
We have a sane default, anything else deserves its own issue. I'm closing this one.
