### ISSUE TITLE
Fix HttpMessageConverters registration

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando-incubator/put-it-to-rest#21]
It seems like the configuration for `HttpMessageConverters` is ignored.

```java
(...)
public final class ClientConfigurationTest {
   (...)

    @Test
    public void shouldRegisterOnlyRegisteredConverters() {
        final List<HttpMessageConverter<?>> converters = ecbRestTemplate.getMessageConverters();
        assertThat(converters, hasSize(2));  // fails because never overwritten
    }
}
```

**Comment by whiskeysierra** [comment]
That's weird. I'm using this in production already. At least I thought I was. Can you create a failing unit test?

**Comment by lukasniemeier-zalando** [comment]
See #22 - I assume this is the expected behavior.

How can you use this library in production if `majorVersion < 1`?!?! /s

**Comment by whiskeysierra** [comment]
> How can you use this library in production if majorVersion < 1?!?! /s

![We do it live](http://www.lolwithme.org/wp-content/uploads/WellDoItLive.jpg)

**Comment by lukasniemeier-zalando** [comment]
That's the spirit :godmode:
