### ISSUE TITLE
Time to Live on AsyncHttpClient

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando-incubator/put-it-to-rest#28]
Referencing #2 we should also set a `timeToLive` for connections of the `AsyncHttpClient`.

**Comment by lukasniemeier-zalando** [comment]
Via pull request to https://github.com/apache/httpasyncclient ?

**Comment by whiskeysierra** [comment]
No longer needed since I switched back to HttpClient (non-async) but we now have an adapter to comply with AsyncClientHttpRequestFactory, i.e. HttpClient + Executor.
