### ISSUE TITLE
Warning on Boot

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando-incubator/put-it-to-rest#30]
If you integrate *put-it-to-rest* into a typical spring-boot application the following warning is emitted on boot.

    ConfigurationClassPostProcessor  : Cannot enhance @Configuration bean definition 'restClientPostProcessor' since its singleton instance has been created too early. The typical cause is a non-static @Bean method with a BeanDefinitionRegistryPostProcessor return type: Consider declaring such methods as 'static'.

Minimal example is adding *put-it-to-rest* as a dependency to https://github.com/spring-guides/gs-spring-boot.git.

**Comment by whiskeysierra** [comment]
I've seen this before. Any idea how to solve it? Declaring it static didn't work for me last time I tried.

**Comment by lukasniemeier-zalando** [comment]
No - it seems like you did everything the warning suggested one to do. Do you know what "enhance" means?

**Comment by whiskeysierra** [comment]
iirc it's adding support for this feature where you can directly call other bean methods and Spring ensures that you will get back the same singleton as that bean would produce anyway.
