### ISSUE TITLE
Extend default configuration (STUPS)

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando-incubator/put-it-to-rest#32]
Our current (Java) configuration looks like this

```java
@Configuration
public class LoggingConfiguration {

    final Pattern pattern = Pattern.compile("(?:(\"(?:access_token|open_id|id_token)\")\\s*\\:\\s*)\".+?\"");
    @Bean
    public BodyObfuscator bodyObfuscator() {
        return ((contentType, body) -> pattern.matcher(body).replaceAll("$1\"XXX\""));
    }
}
```

Do we want to integrate this into *put-it-to-rest*?

**Comment by whiskeysierra** [comment]
> Do we want to integrate this into put-it-to-rest?

We have a chicken-egg-problem, because we both auto configurations (RestClientAutoConfiguration and LogbookAutoConfiguration) depend on each other then: The one needs the interceptor the other needs the body obfuscator.

**Comment by whiskeysierra** [comment]
We should also look at the content type before we do something like that. Or can we even look at the URL? Is this for token generation or verification?
