### ISSUE TITLE
Make tracer instances configurable

### ISSUE THREAD

**Issue by matusewicz** [zalando-incubator/put-it-to-rest#57]
As application using put-it-to-rest
I want to configure all my tracer instances
So that put-it-to-rest can pass those to other libraries like logbook.

As far as I understand, put-it-to-rest creates one singleton tracer instance via auto configuration and passes it to logbook. Other Tracer instances that are defined somewhere else in the code won't be picked up. 
It would be nice to be able to pass those custom Tracer instances as well, because it may happen that you need to start a new Trace in a total different code path than the one that is executed by the "autoconfigured" Tracer instance.

**Comment by whiskeysierra** [comment]
Can you describe your use case a little bit more? Why do you need two tracers?

**Comment by matusewicz** [comment]
Yes sure:
The standard tracer provided by auto configuration starts the trace when processing an servlet request, right?
But what about code that doesn't get triggered by an servlet request? We have backend jobs that run asynchronously and are not bound to any servlet request. Those jobs are using riptide to communicate with other services. We create there new instances of Tracer to map riptide logging to some context specific values. In those jobs we need to create a new Tracer instance as we can't use the default one because they do not share the same code path.

**Comment by whiskeysierra** [comment]
You can use the default one. If you are using `@Scheduled` together with the [`TracerSchedulingAutoConfiguration`](https://github.com/zalando/tracer/blob/master/tracer-spring-boot-starter/src/main/java/org/zalando/tracer/spring/TracerSchedulingAutoConfiguration.java) everything should work out of the box. A tracer instance doesn't care whether it's used in a servlet environment, in a background job or both.

**Comment by lukasniemeier-zalando** [comment]
Imagine you want two `Tracer` instances with different life cycles, i.e. they start and stop their `Traces` at different times in point. How can we expose both to the executor wrapping of logbook?

**Comment by whiskeysierra** [comment]
Summary of an internal discussion:

> Having a custom generator that defaults to an empty string is the safest way to do that. Registering that using configuration requires a custom `GeneratorResolver` based on [the default](https://github.com/zalando/tracer/blob/master/tracer-spring-boot-starter/src/main/java/org/zalando/tracer/spring/DefaultGeneratorResolver.java).
